collections_config:
  config_default:
    path: config/_default
    name: Config Default
    icon: chair_alt
  content_en_posts_post_lite_four:
    path: content/en/posts/post-lite-four
    name: Content En Posts Post Lite Four
    icon: content_paste_go
  content_en_posts_post_lite_one:
    path: content/en/posts/post-lite-one
    name: Content En Posts Post Lite One
    icon: content_paste_off
  content_en_posts_post_lite_three:
    path: content/en/posts/post-lite-three
    name: Content En Posts Post Lite Three
    icon: content_paste_search
  content_en_posts_post_lite_two:
    path: content/en/posts/post-lite-two
    name: Content En Posts Post Lite Two
    icon: content_paste_go
  content_pt_posts_post_lite_four:
    path: content/pt/posts/post-lite-four
    name: Content Pt Posts Post Lite Four
    icon: content_paste_go
  content_pt_posts_post_lite_one:
    path: content/pt/posts/post-lite-one
    name: Content Pt Posts Post Lite One
    icon: content_paste_off
  content_pt_posts_post_lite_three:
    path: content/pt/posts/post-lite-three
    name: Content Pt Posts Post Lite Three
    icon: content_paste_search
  content_pt_posts_post_lite_two:
    path: content/pt/posts/post-lite-two
    name: Content Pt Posts Post Lite Two
    icon: content_paste_go
paths:
  static: static
  uploads: static/uploads
timezone: Asia/Riyadh
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
